### PR TITLE
Migrate pom.xml to GitHub

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jochenw could you please review and eventually merge?

**Comment by khmarbaise** [comment]
Can you please squash your commits together...

**Comment by ppalaga** [comment]
@khmarbaise , as you wish :)

**Comment by ppalaga** [comment]
@khmarbaise 4a09046 squashes all three previous commits together.

**Comment by khmarbaise** [comment]
Can you please check to current master (sorry i have changed a few minutes ago)....

**Comment by ppalaga** [comment]
@khmarbaise no problem

**Comment by ppalaga** [comment]
@khmarbaise, 1ea93e8 is a result of rebasing on the current master plus the new enforcer rules are met now.

**Comment by khmarbaise** [comment]
Thanks.

**Pull request merged**
